sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '12'
script: npm run validate
after_success: node src travis-after-success
branches:
  only:
    - master
